<?php

/**
 * @file
 * Dpl_favorites_list drupal module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dpl_favorites_list_form_dpl_library_agency_list_size_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\dpl_favorites_list\DplFavoritesListSettings $favorites_settings */
  $favorites_settings = \Drupal::service('dpl_favorites_list.settings');

  $form['favorites_list_size_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Favorites list size settings', [], ['context' => 'List size (settings)']),
    '#description' => t('The number of items to display in the favorites list.', [], ['context' => 'List size (settings)']),
    '#tree' => FALSE,
  ];

  $form['favorites_list_size_settings']['favorites_list_size_desktop'] = [
    '#type' => 'number',
    '#title' => t('Favorites list size on desktop', [], ['context' => 'List size (settings)']),
    '#default_value' => $favorites_settings->getListSizeDesktop(),
    '#min' => 1,
    '#step' => 1,
    '#required' => TRUE,
  ];

  $form['favorites_list_size_settings']['favorites_list_size_mobile'] = [
    '#type' => 'number',
    '#title' => t('Favorites list size on mobile', [], ['context' => 'List size (settings)']),
    '#default_value' => $favorites_settings->getListSizeMobile(),
    '#min' => 1,
    '#step' => 1,
    '#required' => TRUE,
  ];

  $form['#submit'][] = 'dpl_favorites_list_handler_submit';
}

/**
 * Custom submit callback.
 *
 * @param array<mixed> $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function dpl_favorites_list_handler_submit(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\dpl_favorites_list\DplFavoritesListSettings $favorites_settings */
  $favorites_settings = \Drupal::service('dpl_favorites_list.settings');

  \Drupal::service('config.factory')
    ->getEditable($favorites_settings->getConfigKey())
    ->set('favorites_list_size_desktop', $form_state->getValue('favorites_list_size_desktop'))
    ->set('favorites_list_size_mobile', $form_state->getValue('favorites_list_size_mobile'))
    ->save();
}
