<?php

/**
 * @file
 * Dpl_patron_menu drupal module file.
 *
 * Renders the patron menu.
 */

use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * Implements template_preprocess_page().
 *
 * @param mixed[] $variables
 *   Theme variables.
 */
function dpl_patron_menu_preprocess_page(array &$variables): void {
  $blockManager = \Drupal::getContainer()->get('plugin.manager.block');

  /** @var \Drupal\dpl_patron_menu\Plugin\Block\PatronMenuBlock $plugin_block */
  $plugin_block = $blockManager->createInstance('dpl_menu_block', []);

  $access_result = $plugin_block->access(\Drupal::currentUser());
  if (is_object($access_result) && $access_result->isForbidden() || is_bool($access_result) && !$access_result) {
    throw new AccessDeniedHttpException();
  }

  $variables['patron'] = [
    'menu' => $plugin_block->build(),
  ];
}
