<?php

/**
 * @file
 * Contains dpl_library_agency.module.
 */

use Drupal\dpl_library_agency\Form\GeneralSettingsForm;
use Drupal\dpl_library_agency\GeneralSettings;

/**
 * Implements hook_dpl_protected_nodes_get_protected_nodes().
 */
function dpl_library_agency_dpl_protected_nodes_get_protected_nodes(): array {
  return dpl_protected_nodes_get_context(GeneralSettingsForm::class, 'dpl_library_agency.general_settings');

}

/**
 * Implements hook_preprocess_page().
 */
function dpl_library_agency_preprocess_page(array &$variables): void {
  $config = \Drupal::config('dpl_library_agency.general_settings');
  $variables['opening_hours_url'] = $config->get('opening_hours_url') ?? GeneralSettings::OPENING_HOURS_URL;
}

/**
 * Used as dynamic list options (allowed_values_function) for a field.
 *
 * See field.storage.node.field_agency_branch_id.yml for more info.
 *
 * @return array<string, string>
 *   The options, used in field_agency_branch_id dropdown.
 */
function dpl_library_agency_field_agency_branch_id_options(): array {
  $options = [];

  try {
    $repository = DrupalTyped::service(FbsBranchRepository::class, 'dpl_library_agency.branch.repository.fbs');
    $branches = $repository->getBranches();

    foreach ($branches as $branch) {
      $options[$branch->id] = "$branch->title ($branch->id)";
    }

    return $options;
  }
  catch (\Exception) {
    return [];
  }
}

