<?php

/**
 * @file
 * DPL Paragraphs tweaks.
 */

use Drupal\Core\Url;
use Drupal\dpl_react_apps\Controller\DplReactAppsController;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\paragraphs\ParagraphInterface;
use function Safe\parse_url;
use function Safe\preg_match;

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adds the absolute base URL to all paragraph entities. This is used to
 * construct absolute paths for assets like icons in the paragraph templates.
 */
function dpl_paragraphs_preprocess_paragraph(array &$variables): void {
  if (isset($variables['paragraph'])) {
    $variables['absoluteBaseUrl'] = \Drupal::request()->getSchemeAndHttpHost();
  }
}

/**
 * Implements hook_preprocess_paragraph__TYPE() for paragraph--links.html.twig.
 *
 * Prepares variables for paragraph--links.html.twig template.
 */
function dpl_paragraphs_preprocess_paragraph__links(array &$variables): void {

  $url_generator = \Drupal::service('url_generator');

  // To infer if a link is downloadable with we have a basic approach, with
  // various limitations. It's important to know, that internal files in
  // project, will be uploaded through the media library using a seperate
  // paragraph. As such the check here is primarily for external links to
  // downloadable files. The approach here checks the URL's file extension to
  // determine if it's a downloadable file. The fallback of an external file
  // not being recognized as downloadable, is to treat it as an external link.
  // Limitations include:
  // 1. URLs endings does not guarantee the content is downloadable.
  // 2. Some downloadable content may not have a typical file extension.
  // 3. Does not consider server responses that dictates downloadability.
  $downloadable_file_extensions = 'pdf|docx|txt|png|jpg|jpeg|gif|csv|xls|xlsx|ppt|pptx';

  // Generate base paths for predefined routes (search and advanced search).
  $search_base_path = $url_generator->generateFromRoute('dpl_react_apps.search_result', [], ['absolute' => FALSE]);
  $advanced_search_base_path = $url_generator->generateFromRoute('dpl_react_apps.advanced_search', [], ['absolute' => FALSE]);

  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->hasField('field_link') && !$paragraph->get('field_link')->isEmpty()) {

    $items = $paragraph->get('field_link')->getValue();
    $variables['links'] = [];

    foreach ($items as $item) {

      $url = Url::fromUri($item['uri']);

      // Get the normalized path. If null, default to an empty string.
      $parsed_url = parse_url($url->toString(), PHP_URL_PATH);
      $normalized_path = is_null($parsed_url) ? '' : rtrim($parsed_url, '/');

      $link_type = 'internal';

      if ($url->isExternal()) {
        if (preg_match('/\.(' . $downloadable_file_extensions . ')(\?.*)?$/i', $normalized_path)) {
          $link_type = 'download';
        }
        else {
          $link_type = 'external';
        }
      }
      elseif ($normalized_path === $search_base_path || $normalized_path === $advanced_search_base_path) {
        $link_type = 'search';
      }

      $linkIconClass = ($link_type === 'internal') ? 'link-with-icon__icon--rotate-180' : '';

      $attributes = [
        'internal' => ['target' => '_self', 'iconFile' => 'ArrowBack', 'iconFolder' => 'collection'],
        'external' => ['target' => '_blank', 'iconFile' => 'icon-external-link', 'iconFolder' => 'basic'],
        'download' => ['target' => '_blank', 'iconFile' => 'Ebook', 'iconFolder' => 'collection'],
        'search' => ['target' => '_self', 'iconFile' => 'SearchBooks', 'iconFolder' => 'collection'],
      ][$link_type];

      $variables['links'][] = [
        'href' => $url->toString(),
        'linkText' => $item['title'],
        'linkType' => $link_type,
        'target' => $attributes['target'],
        'iconFile' => $attributes['iconFile'],
        'iconFolder' => $attributes['iconFolder'],
        'linkIconClass' => $linkIconClass,
      ];
    }
  }
}

/**
 * Implements theme_preprocess_paragraph__NAME().
 *
 * On the 'medias' paragraph, a possible second image should have a different
 * image-style. We do this, by setting a different view mode on the paragraph.
 */
function dpl_paragraphs_preprocess_paragraph__medias(array &$variables): void {
  $paragraph = $variables['paragraph'] ?? NULL;
  $view_mode = $variables['view_mode'] ?? NULL;

  if ($view_mode === 'preview' ||
      !($paragraph instanceof Paragraph) ||
      (empty($variables['content']['field_medias'][1])) ||
      (!$paragraph->hasField('field_medias'))) {
    return;
  }

  $alternative_images = $paragraph->get('field_medias')->view('alternative');
  $variables['content']['field_medias'][1] = $alternative_images[1] ?? NULL;
}

/**
 * Implements hook_preprocess_paragraph__TYPE().
 *
 * Prepares variables for paragraph--recommendation.html.twig template.
 *
 * If the paragraph has a title or description, we use the recommended-material
 * React app. Otherwise, we use the recommendation React app.
 */
function dpl_paragraphs_preprocess_paragraph__recommendation(array &$variables): void {

  $paragraph = $variables['paragraph'] ?? NULL;
  if (!($paragraph instanceof ParagraphInterface) || !$paragraph->hasField('field_work_id') || $paragraph->get('field_work_id')->isEmpty()) {
    return;
  }

  $work_id = $paragraph->get('field_work_id')->getString();
  // Check for the existence of additional fields.
  if ($paragraph->hasField('field_recommendation_title') &&
    $paragraph->hasField('field_recommendation_description') &&
    $paragraph->hasField('field_image_position_right')) {

    $paragraph_title = $paragraph->get('field_recommendation_title')->getString();
    $paragraph_description = $paragraph->get('field_recommendation_description')->getString();
    $paragraph_image_position_right = $paragraph->get('field_image_position_right')->getString();

    if (!empty($paragraph_title) || !empty($paragraph_description)) {
      // The URL is only needed for the recommended-material app.
      $material_url_object = Url::fromRoute('dpl_react_apps.work', ['wid' => $work_id], ['absolute' => TRUE]);
      $material_url = $material_url_object->toString();

      $variables['react_app'] = [
        '#theme' => 'dpl_react_app',
        '#name' => 'recommended-material',
        '#data' => [
          'wid' => $work_id,
        ] + DplReactAppsController::externalApiBaseUrls(),
        '#material_url' => $material_url,
        '#position_image_right' => $paragraph_image_position_right,
      ];
    }
    else {
      // Align React's prop type: String '1' for true, boolean false otherwise.
      $paragraph_image_position_right = $paragraph_image_position_right === '1' ? '1' : FALSE;
      $variables['react_app'] = [
        '#theme' => 'dpl_react_app',
        '#name' => 'recommendation',
        '#data' => [
          'wid' => $work_id,
          'position-image-right' => $paragraph_image_position_right,
        ] + DplReactAppsController::externalApiBaseUrls(),
      ];
    }
  }
}
