docker-compose-yaml: docker-compose.yml

project: tbd-core-test01

tasks:
  post-rollout:
    - run:
        name: If drupal is not installed
        command: |
            if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ]; then
                drush si --existing-config -y
            fi
        service: cli
        shell: bash
    - run:
        name: drush deploy
        command: |
            if [[ -f config/sync/system.site.yml ]]; then
                echo "Config detected, doing a drush deploy"
                drush deploy
            else
                echo "No config detected, clearing cache"
                drush cr
            fi
        service: cli

environments:
  mains:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli

container-registries:
  github:
    username: any-user-works
    # The password gets replaced with the value of an lagoon project environment-
    # variable during lagoons build/deploy process.
    password: GITHUB_REGISTRY_CREDENTIALS
    url: ghcr.io
