docker-compose-yaml: docker-compose.yml

project: dpl-cms-core

tasks:
  post-rollout:
    - run:
        name: If drupal is not installed
        command: |
          if tables=$(drush sqlq "show tables like 'node';") && [ -z "$tables" ]; then
            # Install and set the admin password to a Lagoon variable if it exists.
            if [[ -n $PR_DRUPAL_PWD ]]; then
              drush si --existing-config -y --account-pass=$PR_DRUPAL_PWD
            else
            # Otherwise install and let drush generate a password.
              drush si --existing-config -y
            fi

            # Practice shows that the cache needs to be cleared to avoid
            # configuration errors even after a site install.
            drush cr
          fi
        service: cli
        shell: bash
    - run:
        name: drush deploy
        command: |
          if [[ -f config/sync/system.site.yml ]]; then
            echo "Config detected, doing a drush deploy"
            drush deploy

          # Purge all varnish cache to make sure
          # that new changes will come through
          # eg. js assets.
          echo "...and clearing the external cache."
          drush cache:rebuild-external -y || true
          else
            echo "No config detected, clearing cache"
            drush cr
          fi
        service: cli
    - run:
        # We need this because if we create the directory before volume mount
        # it will be gone.
        name: Create module upload directory in public files
        command: |
          if [[ ! -d "web/sites/default/files/modules_local" ]]; then
            echo "Creating directory for module uploads"
            mkdir web/sites/default/files/modules_local
          fi
        service: cli
    - run:
        name: Import translations
        command: |
          drush locale-check
          drush locale-update
        service: cli
    - run:
        name: Create test users
        command: |
          drush user:create editor --password="$PR_DRUPAL_PWD"
          drush user:role:add 'editor' editor

          drush user:create administrator --password="$PR_DRUPAL_PWD"
          drush user:role:add 'administrator' administrator

          drush user:create mediator --password="$PR_DRUPAL_PWD"
          drush user:role:add 'mediator' mediator

          drush user:create local_administrator --password="$PR_DRUPAL_PWD"
          drush user:role:add 'local_administrator' local_administrator

          drush user:create patron --password="$PR_DRUPAL_PWD"
          drush user:role:add 'patron' patron
        service: cli

environments:
  main:
    cronjobs:
    - name: drush cron
      schedule: "M/15 * * * *"
      command: drush cron
      service: cli
    - name: import translations
      # TODO Consider if translation checking frequency should be reduced.
      # A high frequency is used to ensure quick turnaround time during
      # development. Updating (or checking) translations could have side effects on
      # caching etc. and once things have settled down a lower frequency may be
      # more appropriate.
      schedule: "M/30 * * * *"
      command: drush locale-check && drush locale-update
      service: cli
  pr-886:
    cronjobs:
    - name: drush cron
      schedule: "M/15 * * * *"
      command: drush cron
      service: cli
    - name: import translations
      # Quite frequent translation import because of businezz.
      schedule: "M/2 * * * *"
      command: drush locale-check && drush locale-update
      service: cli
