# This is a go-task file for various developer tasks
# e.g. building docker images and setting up local development.
# You can read about the Task files here: https://taskfile.dev.
version: '3'

dotenv: [".task.env"]

vars:
  REGISTRY: '{{.REGISTRY | default "ghcr.io"}}'
  ORG: '{{.ORG | default "danskernesdigitalebibliotek"}}'
  COMMIT_COUNT:
    sh: git rev-list --count main
  BUILD_NUMBER: '{{.BUILD_NUMBER | default .COMMIT_COUNT }}'
  REPOSITORY_URL: '{{.REPOSITORY_URL | default "git@github.com:{{ .ORG }}/dpl-cms.git"}}'
  REPOSITORY_DIR: "core_repository"
  DOCKER_IMAGE_NAMESPACE: '{{.DOCKER_IMAGE_NAMESPACE | default "dpl-cms"}}'
  DOCKER_IMAGE_PREFIX: "{{ .REGISTRY }}/{{ .ORG }}/{{ .DOCKER_IMAGE_NAMESPACE }}"
  DOCKER_IMAGE_DIR: "docker"
  IMAGE_SOURCE: "{{ .DOCKER_IMAGE_PREFIX }}-source:{{ .BUILD_NUMBER }}"

tasks:
  ghcr:login:
    summary: Login into Github Container Registry
    cmds:
      - echo {{ .CR_PAT }} | docker login {{ .REGISTRY }} -u username-not-used --password-stdin
    preconditions:
      - sh: "[ ! -z {{.CR_PAT}} ]"
        msg: "Env variable CR_PAT is not set or empty."

  composer:install:
    summary: Install drupal.
    cmds:
      - composer install
    preconditions:
  
  source:build:
    summary: Build core source image.
    deps: [composer:install]
    cmds:
      - docker build -f {{ .DOCKER_IMAGE_DIR }}/source.dockerfile --tag {{ .IMAGE_SOURCE }} .

  source:push:
    summary: Push core source image to container registry.
    deps: [ghcr:login]
    cmds:
      - docker push {{ .IMAGE_SOURCE }}

  source:deploy:
    desc: Build and push core source docker image.
    cmds:
      - task: composer:install
      - task: source:build
      - task: source:push