version: '3'

dotenv: [".task.env"]

vars:
  REGISTRY: '{{.REGISTRY | default "ghcr.io"}}'
  ORG: '{{.ORG | default "danskernesdigitalebibliotek"}}'
  COMMIT_COUNT:
    sh: git rev-list --count main
  BUILD_NUMBER: '{{.BUILD_NUMBER | default .COMMIT_COUNT }}'
  REPOSITORY_URL: '{{.REPOSITORY_URL | default "git@github.com:{{ .ORG }}/dpl-cms.git"}}'
  REPOSITORY_DIR: "core_repository"
  DOCKER_IMAGE_NAMESPACE: '{{.DOCKER_IMAGE_NAMESPACE | default "dpl-cms"}}'
  DOCKER_IMAGE_PREFIX: "{{ .REGISTRY }}/{{ .ORG }}/{{ .DOCKER_IMAGE_NAMESPACE }}"
  DOCKER_IMAGE_DIR: "docker"
  IMAGE_SOURCE: "{{ .DOCKER_IMAGE_PREFIX }}-source:{{ .BUILD_NUMBER }}"

tasks:
  ghcr:login:
    summary: Login into Github Container Registry
    cmds:
      - echo {{ .CR_PAT }} | docker login {{ .REGISTRY }} -u username-not-used --password-stdin
    preconditions:
      - sh: "[ ! -z {{.CR_PAT}} ]"
        msg: "Env variable CR_PAT is not set or empty."

  core:source:build:
    summary: Build core source image.
    cmds:
      - docker build -f {{ .DOCKER_IMAGE_DIR }}/source.dockerfile --tag {{ .IMAGE_SOURCE }} .
    preconditions:
      - sh: "[ ! -z {{ .BUILD_NUMBER }} ]"
        msg: "Env variable BUILD_NUMBER is not set or empty."

  core:source:push:
    summary: Push core source image to container registry.
    deps: [ghcr:login]
    cmds:
      - docker push {{ .IMAGE_SOURCE }}
    preconditions:
      - sh: "[ ! -z {{ .BUILD_NUMBER }} ]"
        msg: "Env variable BUILD_NUMBER is not set or empty."

  core:deploy:
    desc: Build and push core source docker image.
    cmds:
      - task: core:source:build
      - task: core:source:push
    preconditions:
      - sh: "[ ! -z {{.BUILD_NUMBER}} ]"
        msg: "Env variable BUILD_NUMBER is not set or empty."
 