# Schema for the configuration files of the BNF Client module.

bnf_client.settings:
  type: config_object
  label: 'BNF client configuration'
  mapping:
    base_url:
      type: uri
      label: 'BNF server URL'
      constraints:
        IsHttps: ~
        Regex:
          pattern: '/\/$/'
          message: 'URL must end with a /.'
