<?php

/**
 * @file
 * DPL Login module.
 *
 * Handles authentication against Adgangsplatformen.
 */

use Drupal\Core\Site\Settings;
use Drupal\dpl_login\AccessToken;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_openid_connect_userinfo_alter().
 *
 * @param mixed[] $userinfo
 *   User info from external service.
 * @param mixed[] $context
 *   Various openid_connect context. Tokens etc.
 */
function dpl_login_openid_connect_userinfo_alter(array &$userinfo, array $context): void {

  // If we cannot resolve uinque id we cannot continue.
  if (!$id = $userinfo['attributes']['uniqueId'] ?? FALSE) {
    $userinfo = [];
    return;
  }

  $id_hash = crypt($id, Settings::getHashSalt());

  $name = uniqid();
  // Drupal needs an email. We set a unique one to apply to that rule.
  $userinfo['email'] = sprintf('%s@dpl-cms.invalid', $name);
  // Drupal needs a user name. We use the unique id to apply to that rule.
  $userinfo['name'] = $name;
  // openid_connect module needs the sub for creating the auth map.
  $userinfo['sub'] = $id_hash;
}

/**
 * Implements hook_openid_connect_post_authorize().
 */

/**
 * Implements hook_openid_connect_post_authorize().
 *
 * @param \Drupal\Core\Session\AccountInterface $account
 *   User account.
 * @param mixed[] $context
 *   Various openid_connect context. Tokens etc.
 */
function dpl_login_openid_connect_post_authorize(AccountInterface $account, array $context): void {
  $access_token = AccessToken::createFromOpenidConnectContext($context);
  /** @var Drupal\dpl_login\UserTokensProvider $token_provider */
  $token_provider = \Drupal::service('dpl_login.user_tokens');
  $token_provider->setAccessToken($access_token);
}
