dpl_config_upload.upload_form:
  path: "/admin/config/configuration/import"
  defaults:
    _form: 'Drupal\dpl_config_import\Form\UploadForm'
    _title: "Upload configuration"
  requirements:
    _permission: "import configuration,administer modules"
