<?php

/**
 * @file
 * Mobilesearch integration.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\eonext_mobilesearch\Event\EntityActionEvent;
use Drupal\eonext_mobilesearch\Form\MobilesearchNodesExportForm;
use Drupal\eonext_mobilesearch\Mobilesearch\DTO\MobilesearchEntityInterface;

/**
 * Implements hook_entity_insert().
 */
function eonext_mobilesearch_entity_insert(EntityInterface $entity): void {
  $event = new EntityActionEvent($entity, EntityActionEvent::EVENT_ENTITY_INSERT);

  $bundleConfig = \Drupal::config(MobilesearchNodesExportForm::CONFIG_ID);
  $bundleEnabledToPush = (bool) $bundleConfig->get($entity->bundle());

  if ($bundleEnabledToPush && $event->shouldTrigger()) {
    /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $event_dispatcher */
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, EntityActionEvent::EVENT_ENTITY_INSERT);
  }
}

/**
 * Implements hook_entity_update().
 */
function eonext_mobilesearch_entity_update(EntityInterface $entity): void {
  $event = new EntityActionEvent($entity, EntityActionEvent::EVENT_ENTITY_UPDATE);

  $bundleConfig = \Drupal::config(MobilesearchNodesExportForm::CONFIG_ID);
  $bundleEnabledToPush = (bool) $bundleConfig->get($entity->bundle());

  if ($bundleEnabledToPush && $event->shouldTrigger()) {
    /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $event_dispatcher */
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, EntityActionEvent::EVENT_ENTITY_UPDATE);
  }
}

/**
 * Implements hook_entity_delete().
 */
function eonext_mobilesearch_entity_delete(EntityInterface $entity): void {
  $event = new EntityActionEvent($entity, EntityActionEvent::EVENT_ENTITY_DELETE);

  $bundleConfig = \Drupal::config(MobilesearchNodesExportForm::CONFIG_ID);
  $bundleEnabledToPush = (bool) $bundleConfig->get($entity->bundle());

  if ($bundleEnabledToPush && $event->shouldTrigger()) {
    /** @var \Symfony\Component\EventDispatcher\EventDispatcherInterface $event_dispatcher */
    $event_dispatcher = \Drupal::service('event_dispatcher');
    $event_dispatcher->dispatch($event, EntityActionEvent::EVENT_ENTITY_DELETE);
  }
}

/**
 * Implements hook_mobilesearch_push_alter().
 *
 * @param \Drupal\eonext_mobilesearch\Mobilesearch\DTO\NodeEntityDto $payload
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function eonext_mobilesearch_mobilesearch_push_alter(MobilesearchEntityInterface $payload, EntityInterface $entity): void {
  if ($entity->getEntityTypeId() === 'eventinstance') {
    $payload->setNid(20000000 + (int) $payload->getNid());
  }

  $type = $payload->getType();
  $payload->setType(match($type) {
    'page' => 'ding_page',
    'article' => 'ding_news',
    'default' => 'ding_event', // 'default' is the default bundle for events
    default => $type
  });

  // Fields backwards compatibility processing.
  $fields = $payload->getFields();

  $fields_replacement_map = [
    'uid' => 'author',
    'field_branch' => 'og_group_ref',
    'branch' => 'og_group_ref',
    'date' => 'field_ding_event_date',
    'event_teaser_text' => 'field_ding_event_lead',
    'event_teaser_image' => 'field_ding_event_list_image',
    'event_description' => 'field_ding_event_body',
    'event_image' => 'field_ding_event_title_image',
    'event_link_uri' => 'field_ding_event_ticket_link',
    'field_subtitle' => 'field_ding_news_lead',
    'field_teaser_image' => 'field_ding_news_list_image',
  ];

  foreach ($fields_replacement_map as $field => $replacement) {
    if (array_key_exists($field, $fields)) {
      /** @var \Drupal\eonext_mobilesearch\Mobilesearch\DTO\FieldDto $dto_field */
      $dto_field = $fields[$field];
      unset($fields[$field]);
      $fields[$replacement] = $dto_field;
    }
  }

  $removal_map = [
    'vid', 'revision_uid',
    'revision_timestamp', 'revision_log',
    'status', 'promote',
    'sticky', 'default_langcode',
    'revision_default', 'revision_translation_affected',
    'entity_clone_template_active', 'entity_clone_template_image',
  ];
  foreach ($removal_map as $field) {
    unset($fields[$field]);
  }

  $payload->setFields($fields);

  // Taxonomy backwards compatibility processing.
  $taxonomy = $payload->getTaxonomy();

  $fields_replacement_map = [
    'event_categories' => 'field_ding_event_category',
  ];

  foreach ($fields_replacement_map as $field => $replacement) {
    if (array_key_exists($field, $fields)) {
      /** @var \Drupal\eonext_mobilesearch\Mobilesearch\DTO\FieldDto $dto_field */
      $dto_field = $fields[$field];
      unset($fields[$field]);
      $fields[$replacement] = $dto_field;
    }
  }

//  $removal_map = [
//    'vid',
//    'revision_timestamp', 'revision_log',
//    'status', 'promote',
//    'sticky', 'default_langcode',
//    'revision_default', 'revision_translation_affected',
//  ];
//  foreach ($removal_map as $field) {
//    unset($fields[$field]);
//  }

  $payload->setTaxonomy($taxonomy);
}
