<?php

/**
 * @file
 * Primary module hooks for Mapp Intelligence module.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_page_attachments().
 *
 * @param array[] $page
 *   The page render array.
 */
function dpl_mapp_page_attachments(array &$page): void {
  $page['#cache'] = array_merge_recursive($page['#cache'] ?? [], ['contexts' => ['route.name']]);

  $is_admin_route = \Drupal::service('router.admin_context')->isAdminRoute();
  $route_name = \Drupal::routeMatch()->getRouteName();
  $is_excluded_route = in_array($route_name, [
    'dpl_react_apps.search_result',
    'dpl_react_apps.work',
  ]);

  // Disable tracking on admin pages (we are only interested in patron behavior)
  // and on specific routes (some pages should only track data from React apps)
  if ($is_admin_route || $is_excluded_route) {
    return;
  }

  $config = \Drupal::config('dpl_mapp.settings');

  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'] ?? [], $config->getCacheTags());
  if ($config->get('id') && $config->get('domain')) {
    $page['#attached']['library'][] = 'dpl_mapp/dpl_mapp';
    $page['#attached']['drupalSettings']['dpl_mapp'] = [
      'domain' => $config->get('domain'),
      'id' => $config->get('id'),
    ];
  }
}
