<?php

/**
 * @file
 * Primary module hooks for Mapp Intelligence module.
 */

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_page_attachments().
 *
 * @param array[] $page
 *   The page render array.
 */
function dpl_mapp_page_attachments(array &$page): void {
  // Disable tracking on admin pages. We interested in patron - not editor -
  // behavior.
  if (\Drupal::routeMatch()->getRouteObject()?->getOption('_admin_route')) {
    return;
  }

  $config = \Drupal::config('dpl_mapp.settings');

  $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'] ?? [], $config->getCacheTags());
  if ($config->get('id') && $config->get('domain')) {
    $page['#attached']['library'][] = 'dpl_mapp/dpl_mapp';
    $page['#attached']['drupalSettings']['dpl_mapp'] = [
      'domain' => $config->get('domain'),
      'id' => $config->get('id'),
    ];
  }

  if (\Drupal::currentUser()->isAuthenticated()) {
    $page['#attached']['drupalSettings']['dpl_mapp'] = [
      'login' => _dpl_mapp_get_login_method(),
    ];
  }
}

/**
 * Function used for returning logged in method from session.
 *
 * @return string
 *   The login method.
 */
function _dpl_mapp_get_login_method(): string {
  return $_SESSION['logged_in_with'];
}
