<?php
/**
 * PatronSettingsV4Test
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FBS Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DPL\FBS\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PatronSettingsV4Test Class Doc Comment
 *
 * @category    Class
 * @description PatronSettingsV4
 * @package     DPL\FBS
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PatronSettingsV4Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PatronSettingsV4"
     */
    public function testPatronSettingsV4()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notification_protocols"
     */
    public function testPropertyNotificationProtocols()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "on_hold"
     */
    public function testPropertyOnHold()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preferred_language"
     */
    public function testPropertyPreferredLanguage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preferred_pickup_branch"
     */
    public function testPropertyPreferredPickupBranch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receive_email"
     */
    public function testPropertyReceiveEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receive_postal_mail"
     */
    public function testPropertyReceivePostalMail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receive_sms"
     */
    public function testPropertyReceiveSms()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
