<?php

/**
 * @file
 * DPL cookies module.
 */

/**
 * Implements hook_preprocess_media().
 */
function dpl_cookies_preprocess_field__media(array &$variables): void {
  foreach ($variables['items'] as &$item) {
    $item['content']['#attributes']['data-once'] = 'cookieinformation-iframe';
    $item['content']['#attributes']['data-category-consent'] = 'cookie_cat_marketing';
    $item['content']['#attributes']['data-consent-src'] = $item['content']['#attributes']['src'];
  }
}
