<?php

/**
 * @file
 * DPL cookies module.
 */

/**
 * Implements hook_preprocess_media().
 *
 * Adds cookie consent attributes to media video fields.
 */
function dpl_cookies_preprocess_field__media__video(array &$variables): void {
  foreach ($variables['items'] as &$item) {
    if (isset($item['content']['#attributes']['src'])) {
      $item['content']['#attributes']['data-once'] = 'cookieinformation-iframe';
      $item['content']['#attributes']['data-category-consent'] = 'cookie_cat_marketing';
      $item['content']['#attributes']['data-consent-src'] = $item['content']['#attributes']['src'];
      $item['content']['#attributes']['src'] = '';
    }
  }
}
