<?php
/**
 * PatronWithGuardianRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  DanskernesDigitaleBibliotek\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FBS Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DanskernesDigitaleBibliotek\FBS\Model;

use \ArrayAccess;
use \DanskernesDigitaleBibliotek\FBS\ObjectSerializer;

/**
 * PatronWithGuardianRequest Class Doc Comment
 *
 * @category Class
 * @package  DanskernesDigitaleBibliotek\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PatronWithGuardianRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PatronWithGuardianRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'address' => '\DanskernesDigitaleBibliotek\FBS\Model\Address',
        'cpr_number' => 'string',
        'email' => 'string',
        'guardian' => '\DanskernesDigitaleBibliotek\FBS\Model\Guardian',
        'name' => 'string',
        'phone_number' => 'string',
        'pincode' => 'string',
        'preferred_pickup_branch' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'address' => null,
        'cpr_number' => null,
        'email' => null,
        'guardian' => null,
        'name' => null,
        'phone_number' => null,
        'pincode' => null,
        'preferred_pickup_branch' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'cpr_number' => 'cprNumber',
        'email' => 'email',
        'guardian' => 'guardian',
        'name' => 'name',
        'phone_number' => 'phoneNumber',
        'pincode' => 'pincode',
        'preferred_pickup_branch' => 'preferredPickupBranch'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'cpr_number' => 'setCprNumber',
        'email' => 'setEmail',
        'guardian' => 'setGuardian',
        'name' => 'setName',
        'phone_number' => 'setPhoneNumber',
        'pincode' => 'setPincode',
        'preferred_pickup_branch' => 'setPreferredPickupBranch'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'cpr_number' => 'getCprNumber',
        'email' => 'getEmail',
        'guardian' => 'getGuardian',
        'name' => 'getName',
        'phone_number' => 'getPhoneNumber',
        'pincode' => 'getPincode',
        'preferred_pickup_branch' => 'getPreferredPickupBranch'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = $data['address'] ?? null;
        $this->container['cpr_number'] = $data['cpr_number'] ?? null;
        $this->container['email'] = $data['email'] ?? null;
        $this->container['guardian'] = $data['guardian'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['phone_number'] = $data['phone_number'] ?? null;
        $this->container['pincode'] = $data['pincode'] ?? null;
        $this->container['preferred_pickup_branch'] = $data['preferred_pickup_branch'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cpr_number'] === null) {
            $invalidProperties[] = "'cpr_number' can't be null";
        }
        if ($this->container['guardian'] === null) {
            $invalidProperties[] = "'guardian' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['pincode'] === null) {
            $invalidProperties[] = "'pincode' can't be null";
        }
        if ($this->container['preferred_pickup_branch'] === null) {
            $invalidProperties[] = "'preferred_pickup_branch' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return \DanskernesDigitaleBibliotek\FBS\Model\Address|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \DanskernesDigitaleBibliotek\FBS\Model\Address|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets cpr_number
     *
     * @return string
     */
    public function getCprNumber()
    {
        return $this->container['cpr_number'];
    }

    /**
     * Sets cpr_number
     *
     * @param string $cpr_number cpr_number
     *
     * @return self
     */
    public function setCprNumber($cpr_number)
    {
        $this->container['cpr_number'] = $cpr_number;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Must be valid if supplied
     *
     * @return self
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets guardian
     *
     * @return \DanskernesDigitaleBibliotek\FBS\Model\Guardian
     */
    public function getGuardian()
    {
        return $this->container['guardian'];
    }

    /**
     * Sets guardian
     *
     * @param \DanskernesDigitaleBibliotek\FBS\Model\Guardian $guardian guardian
     *
     * @return self
     */
    public function setGuardian($guardian)
    {
        $this->container['guardian'] = $guardian;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The full name of the patron
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string|null $phone_number Must be valid if supplied
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets pincode
     *
     * @return string
     */
    public function getPincode()
    {
        return $this->container['pincode'];
    }

    /**
     * Sets pincode
     *
     * @param string $pincode pincode
     *
     * @return self
     */
    public function setPincode($pincode)
    {
        $this->container['pincode'] = $pincode;

        return $this;
    }

    /**
     * Gets preferred_pickup_branch
     *
     * @return string
     */
    public function getPreferredPickupBranch()
    {
        return $this->container['preferred_pickup_branch'];
    }

    /**
     * Sets preferred_pickup_branch
     *
     * @param string $preferred_pickup_branch Must be a valid branch id (eg. DK-761501)
     *
     * @return self
     */
    public function setPreferredPickupBranch($preferred_pickup_branch)
    {
        $this->container['preferred_pickup_branch'] = $preferred_pickup_branch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


