<?php

/**
 * @file
 * Ddb_react_demo drupal module file.
 *
 * Demonstrates how to use the ddb_react module
 * and render components.
 */

/**
 * Construct button render array.
 *
 * @return mixed[]
 *   Render array with button.
 */
function ddb_react_demo_button(): array {
  $data = [
    'material-list-url' => ddb_react_material_list_url(),
    'id' => '870970-basis:54172613',
    'add-text' => t('Add to checklist'),
    'add-error-text' => t('An error occurred'),
    'add-success-text' => t('Added to checklist'),
    'remove-text' => t('Remove from checklist'),
    'remove-error-text' => t('An error occurred'),
    'remove-success-text' => t('Removed from checklist'),
    'login-url' => '/user/login',
  ];

  return [ddb_react_render('checklist-material-button', $data)];
}
