<?php

/**
 * @file
 * Ddb_react_demo drupal module file.
 *
 * Demonstrates how to use the ddb_react module
 * and render components.
 */

/**
 * Construct button render array.
 *
 * @return mixed[]
 *   Render array with button.
 */
function ddb_react_demo_button(): array {
  $data = [
    'material-list-url' => ddb_react_material_list_url(),
    'id' => 100,
    'add-text' => t('Add to checklist'),
    'add-error-text' => t('An error occurred'),
    'add-success-text' => t('Added to checklist'),
    'remove-text' => t('Remove from checklist'),
    'remove-error-text' => t('An error occurred'),
    'remove-success-text' => t('Removed from checklist'),
      // Obviously we cannot login via google.com.
      // This needs to be corrected with proper a proper url when known.
    'login-url' => 'http://google.com',
  ];

  return [ddb_react_render('checklist-material-button', $data)];
}
