<?php

/**
 * @file
 * Ddb_react_demo drupal module file.
 *
 * Demonstrates how to use the ddb_react module
 * and render components.
 */

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_library_info_alter().
 */
function ddb_react_demo_library_info_alter(array &$libraries, $module) {
  if ($module != 'ddb_react_demo') {
    return;
  }

  // Check if a version json file exists and decode the json configuration.
  if ($library_info_json = file_get_contents('libraries/ddb-react/version.json')) {
    $library_info = Json::decode($library_info_json);
  }
  if (!$library_info || !isset($library_info['version'])) {
    return;
  }

  // Set the version from the assets on all libraries.
  foreach ($libraries as $library) {
    $libraries[$library]['version'] == $library_info['version'];
  }
}

/**
 * Construct button render array.
 *
 * @return array
 *   Render array with button.
 */
function ddb_react_demo_button() {
  $data = [
    'material-list-url' => ddb_react_material_list_url(),
    'id' => 100,
    'add-text' => t('Add to checklist'),
    'add-error-text' => t('An error occurred'),
    'add-success-text' => t('Added to checklist'),
    'remove-text' => t('Remove from checklist'),
    'remove-error-text' => t('An error occurred'),
    'remove-success-text' => t('Removed from checklist'),
      // Obviously we cannot login via google.com.
      // This needs to be corrected with proper a proper url when known.
    'login-url' => 'http://google.com',
  ];

  return [ddb_react_render('checklist-material-button', $data)];
}
