<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_presave().
 *
 * Sets the field_publication_date to the current date
 * if the node is being published or if the publication date is not already set.
 */
function dpl_publication_node_presave(NodeInterface $node): void {
  if (!$node->hasField('field_publication_date')) {
    return;
  }
  /** @var \Drupal\node\NodeInterface|null $original_node */
  $original_node = $node->original;

  // Only update the publication date, if nothing is set, or if the status is
  // moved to 'published'.
  if (($node->get('field_publication_date')->isEmpty()) ||
    $original_node && $node->isPublished() && !$original_node->isPublished()) {
    $current_date = new DrupalDateTime('now');
    $formatted_date = $current_date->format('Y-m-d');
    $node->set('field_publication_date', $formatted_date);
  }
}
