<?php

/**
 * @file
 * Dpl_react_app drupal module file.
 *
 * Is providing theme variables
 * in order to integrate the DPL react apps in the site
 * and various other tasks eg. providing rides and controllers for rendering.
 */

use Drupal\dpl_react_apps\Controller\DplReactAppsController;

/**
 * Implements template_preprocess_page().
 *
 * @param mixed[] $variables
 *   Theme variables.
 */
function dpl_react_apps_preprocess_page(array &$variables): void {
  $options = ['context' => 'Search Header'];

  $data = [
    'search-header' => [
      'search-url' => DplReactAppsController::searchResultUrl(),
      'material-url' => DplReactAppsController::materialUrl(),
      'alt-text' => t('Search field', [], $options),
      'input-placeholder-text' => t('Start typing in order to search', [],
        $options),
      'string-suggestion-author-text' => t('Author', [], $options),
      'string-suggestion-topic-text' => t('Topic', [], $options),
      'string-suggestion-work-text' => t('Work', [], $options),
    ],
  ];

  $variables['search'] = [
    'header' => dpl_react_render('search-header', $data['search-header']),
  ];
}
