<?php

/**
 * @file
 * Dpl_react_app drupal module file.
 *
 * Is providing theme variables
 * in order to integrate the DPL react apps in the site
 * and various other tasks eg. providing rides and controllers for rendering.
 */

use Drupal\dpl_react_apps\Controller\DplReactAppsController;

/**
 * Implements template_preprocess_page().
 *
 * @param mixed[] $variables
 *   Theme variables.
 */
function dpl_react_apps_preprocess_page(array &$variables): void {
  $variables['search'] = [
    'header' => [
      '#theme' => 'dpl_react_app',
      '#name' => 'search-header',
      '#data' => [
        'search-url' => DplReactAppsController::searchResultUrl(),
        'material-url' => DplReactAppsController::materialUrl(),
        'advanced-search-url' => DplReactAppsController::advancedSearchUrl(),
        // Text.
        'autosuggest-animated-series-category-text' => t('Animated series', [], ['context' => 'Search Header']),
        'autosuggest-audio-book-category-text' => t('Audio books', [], ['context' => 'Search Header']),
        'autosuggest-book-category-text' => t('Books', [], ['context' => 'Search Header']),
        'autosuggest-ebook-category-text' => t('E-books', [], ['context' => 'Search Header']),
        'autosuggest-film-category-text' => t('Movies', [], ['context' => 'Search Header']),
        'autosuggest-game-category-text' => t('Games', [], ['context' => 'Search Header']),
        'autosuggest-music-category-text' => t('Music', [], ['context' => 'Search Header']),
        'et-al-text' => t('et al.', [], ['context' => 'Search Header']),
        'in-text' => t('in', [], ['context' => 'Search Header']),
        'input-placeholder-text' => t('Start typing in order to search', [], ['context' => 'Search Header']),
        'loading-text' => t('Loading', [], ['context' => 'Search Header']),
        'search-header-icon-alt-text' => t('Search button', [], ['context' => 'Search Header']),
        'search-header-input-label' => t('Search header input', [], ['context' => 'Search Header']),
        'search-no-valid-characters-error-text' => t('Input must contain at least one non-whitespace character.', [], ['context' => 'Search Header']),
        'string-suggestion-author-text' => t('Author', [], ['context' => 'Search Header']),
        'string-suggestion-topic-text' => t('Topic', [], ['context' => 'Search Header']),
        'string-suggestion-work-text' => t('Work', [], ['context' => 'Search Header']),
      // Add external API base urls.
      ] + DplReactAppsController::externalApiBaseUrls(),
    ],
  ];

}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param mixed[] $variables
 *   The variables for the theme hook.
 */
function dpl_react_apps_preprocess_dpl_react_app(array &$variables): void {
  // Since we need these texts in all the apps we add them here.
  $variables['attributes'] += [
    'data-alert-error-close-text' => t('Close', [], ['context' => 'React apps (Global error handling)']),
    'data-alert-error-message-text' => t('An error occurred', [], ['context' => 'React apps (Global error handling)']),
  ];
}
