<?php
/**
 * DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * DPL CMS - REST API
 *
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace DanskernesDigitaleBibliotek\CMS\Api\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData model.
 *
 * @package DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author  OpenAPI Generator team
 */

class DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData 
{
        /**
     * The end date of the repetition. If the end date is not on the same week day as the first instance then the preceding occurrence of the weekday will be the last instance. &lt;br/&gt;&lt;br/&gt;This field must be provided if type is &#39;weekly&#39;
     *
     * @var \DateTime|null
     * @SerializedName("end_date")
     * @Assert\Type("\Date")
     * @Type("DateTime<'Y-m-d'>")
     */
    protected ?\DateTime $endDate = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->endDate = array_key_exists('endDate', $data) ? $data['endDate'] : $this->endDate;
        }
    }

    /**
     * Gets endDate.
     *
     * @return \DateTime|null
     */
    public function getEndDate(): ?\DateTime
    {
        return $this->endDate;
    }



    /**
     * Sets endDate.
     *
     * @param \DateTime|null $endDate  The end date of the repetition. If the end date is not on the same week day as the first instance then the preceding occurrence of the weekday will be the last instance. <br/><br/>This field must be provided if type is 'weekly'
     *
     * @return $this
     */
    public function setEndDate(?\DateTime $endDate = null): self
    {
        $this->endDate = $endDate;

        return $this;
    }
}


