<?php
/**
 * DplOpeningHoursCreatePOSTRequestRepetition
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * DPL CMS - REST API
 *
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace DanskernesDigitaleBibliotek\CMS\Api\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DplOpeningHoursCreatePOSTRequestRepetition model.
 *
 * @package DanskernesDigitaleBibliotek\CMS\Api\Model
 * @author  OpenAPI Generator team
 */

class DplOpeningHoursCreatePOSTRequestRepetition 
{
        /**
     * A serial unique id of the repetition. All instances with the same id belongs to the same repetition.
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $id = null;

    /**
     * If/how the instance should be repeated in the future: &lt;br/&gt; - single: The instance should not be repeated &lt;br/&gt; - weekly: The instance should be repeated weekly from the first day of the repetition until the provided end date. The week day of the first instance defines which weekday should be used for the repeated instances.
     *
     * @var string|null
     * @SerializedName("type")
     * @Assert\NotNull()
     * @Assert\Choice({ "none", "weekly" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $type = null;

    /**
     * @var DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData|null
     * @SerializedName("weekly_data")
     * @Assert\Type("DanskernesDigitaleBibliotek\CMS\Api\Model\DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData")
     * @Type("DanskernesDigitaleBibliotek\CMS\Api\Model\DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData")
     */
    protected ?DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData $weeklyData = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->type = array_key_exists('type', $data) ? $data['type'] : $this->type;
            $this->weeklyData = array_key_exists('weeklyData', $data) ? $data['weeklyData'] : $this->weeklyData;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }



    /**
     * Sets id.
     *
     * @param int|null $id  A serial unique id of the repetition. All instances with the same id belongs to the same repetition.
     *
     * @return $this
     */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }



    /**
     * Sets type.
     *
     * @param string|null $type  If/how the instance should be repeated in the future: <br/> - single: The instance should not be repeated <br/> - weekly: The instance should be repeated weekly from the first day of the repetition until the provided end date. The week day of the first instance defines which weekday should be used for the repeated instances.
     *
     * @return $this
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets weeklyData.
     *
     * @return DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData|null
     */
    public function getWeeklyData(): ?DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData
    {
        return $this->weeklyData;
    }



    /**
     * Sets weeklyData.
     *
     * @param DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData|null $weeklyData
     *
     * @return $this
     */
    public function setWeeklyData(?DplOpeningHoursListGET200ResponseInnerRepetitionWeeklyData $weeklyData = null): self
    {
        $this->weeklyData = $weeklyData;

        return $this;
    }
}


