<?php

/**
 * @file
 * Primary module hooks for dpl_webform_configuration module.
 */

use Drupal\webform\Entity\Webform;

/**
 * Implements hook_ENTITY_TYPE_create() for webform.
 */
function dpl_webform_configuration_webform_create(Webform $webform): void {
  // We want to avoid saving sensitive information from users because of GDPR.
  // Therefore we disable saving of results for all new webforms.
  $webform->setSetting('results_disabled', TRUE);
}
