<?php

/**
 * @file
 * Primary module hooks for dpl_webform_configuration module.
 */

use Drupal\webform\Entity\Webform;

/**
 * Implements hook_ENTITY_TYPE_create() for webform.
 */
function dpl_webform_configuration_webform_create(Webform $webform): void {
  // We want to avoid saving sensitive information from users because of GDPR.
  // Therefore we disable saving of results for all new webforms.
  $webform->setSetting('results_disabled', TRUE);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dpl_webform_configuration_preprocess_input__submit(array &$variables): void {
  $original_classes = $variables['attributes']['class'];

  if (in_array('webform-button--submit', $original_classes)) {
    $variables['attributes']['class'] = array_merge($original_classes, [
      'btn-primary',
      'btn-filled',
      'btn-small',
      'arrow__hover--right-small',
      'dpl-button',
    ]);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function dpl_webform_configuration_theme_suggestions_form_element_alter(array &$suggestions, array $variables): void {
  if (isset($variables['element']['#webform_element'])) {
    $suggestions[] = 'form_element__webform';
  }
}
