<?php

/**
 * @file
 * Dpl_fees drupal module file.
 *
 * Renders the fees list.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\dpl_fees\DplFeesSettings;

/**
 * Implements hook_dpl_react_apps_data().
 */
function dpl_fees_dpl_react_apps_data(array &$data): void {
  $data['urls'] += [
    'fee-page' => dpl_react_apps_ensure_url_is_string(
      Url::fromRoute('dpl_fees.list', [], ['absolute' => TRUE])->toString()
    ),
  ];
}

/**
 * Implements hook_form_alter().
 */
function dpl_fees_form_dpl_library_agency_list_size_settings_form_alter (array &$form, FormStateInterface $form_state): void
{
  $config = \Drupal::service('config.factory')
    ->getEditable('dpl_library_agency.list_size_settings');

  $form['fees_list_size_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Fees list size settings', [], ['context' => 'List size (settings)']),
    '#description' => t('The number of items to display in the fees list.', [], ['context' => 'List size (settings)']),
    '#tree' => FALSE,
  ];

  $form['fees_list_size_settings']['fees_list_size_desktop'] = [
    '#type' => 'number',
    '#title' => t('Fees list size on desktop', [], ['context' => 'List size (settings)']),
    '#default_value' => $config->get('fees_list_size_desktop') ?? DplFeesSettings::FEES_LIST_SIZE_DESKTOP,
    '#min' => 0,
    '#step' => 1,
  ];

  $form['fees_list_size_settings']['fees_list_size_mobile'] = [
    '#type' => 'number',
    '#title' => t('Fees list size on mobile', [], ['context' => 'List size (settings)']),
    '#default_value' => $config->get('fees_list_size_mobile') ?? DplFeesSettings::FEES_LIST_SIZE_MOBILE,
    '#min' => 0,
    '#step' => 1,
  ];

  $form['#submit'][] = 'dpl_fees_handler_submit';
}

/**
 * Custom submit callback.
 */
function dpl_fees_handler_submit(array &$form, FormStateInterface $form_state): void {
  \Drupal::service('config.factory')
    ->getEditable('dpl_library_agency.list_size_settings')
    ->set('fees_list_size_desktop', $form_state->getValue('fees_list_size_desktop'))
    ->set('fees_list_size_mobile', $form_state->getValue('fees_list_size_mobile'))
    ->save();
}
