field.value.dpl_fbi_cql_search:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.value.dpl_fbi_work_id:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.field_type.dpl_fbi_cql_search:
  type: mapping
  label: 'CQL Search field'
  mapping:
    value:
      type: string
      label: 'CQL query'
    link:
      type: string
      label: 'Link to search'
    location:
      type: string
      label: 'Location filter'
    sublocation:
      type: string
      label: 'Sub-location filter'
    onshelf:
      type: boolean
      label: 'On-shelf filter'
    first_accession_date_value:
      type: string
      label: 'First accession date filter: Value'
    first_accession_date_operator:
      type: string
      label: 'First accession date filter: Operator'

field.widget.settings.dpl_fbi_cql_search:
  type: mapping
  label: 'CQL Search field widget settings'
  mapping:
    advanced:
      type: boolean
      label: 'Enable advanced fields'
