<?php

/**
 * @file
 * DPL article module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function dpl_article_preprocess_node(array &$variables): void {
  $node = $variables['node'] ?? NULL;

  // Process only if the node is a valid Node entity.
  if (!($node instanceof Node)) {
    return;
  }

  // Override author name if the 'show overwrite author' field is set.
  $has_override = $node->get('field_show_overwrite_author')
    ->getString() === '1';
  if ($has_override) {
    $variables['author_name'] = $node->get('field_overwrite_author')
      ->getString();
  }
}

/**
 * Implements hook_form_alter().
 *
 * Modifies node forms to control the visibility of certain fields.
 *
 * @param array<mixed> $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param string $form_id
 *   The unique identifier of the form.
 */
function dpl_article_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Target only node creation or edit forms.
  // They follow this format: node_CT_edit_form / node_CT_form.
  if (!str_starts_with($form_id, 'node_') ||
    !(str_ends_with($form_id, '_edit_form') || str_ends_with($form_id, '_form'))) {
    return;
  }

  // Toggle visibility of 'overwrite author' field based on a checkbox.
  $form['field_overwrite_author']['#states'] = [
    'visible' => [':input[name="field_show_overwrite_author[value]"]' => ['checked' => TRUE]],
  ];
}
