<?php

/**
 * @file
 * Functionality for DPL cache settings.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar_alter().
 *
 * Displaying the DPL CMS version in the secondary admin toolbar.
 *
 * @param array<mixed> $items
 *   See hook_toolbar_alter().
 */
function dpl_cache_settings_toolbar_alter(array &$items): void {
  $items['cache_clear'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Clear caches', [], ['context' => 'DPL admin UX']),
      '#url' => Url::fromRoute('dpl_cache_settings.settings_form'),
      '#attributes' => [
        'class' => ['toolbar-icon', 'toolbar-icon-cache-clear'],
      ],
    ],
  ];
}
