<?php
/**
 * ExternalAgencyidPatronPatronidApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FBS Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DPL\FBS\Test\Api;

use \DPL\FBS\Configuration;
use \DPL\FBS\ApiException;
use \DPL\FBS\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExternalAgencyidPatronPatronidApiTest Class Doc Comment
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExternalAgencyidPatronPatronidApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getFeesV2
     *
     * List of fees in FBS for the patron with all available information about the fee..
     *
     */
    public function testGetFeesV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
