<?php
/**
 * ExternalV1AgencyidPatronsPatronidReservationsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FBS Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DPL\FBS\Test\Api;

use \DPL\FBS\Configuration;
use \DPL\FBS\ApiException;
use \DPL\FBS\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExternalV1AgencyidPatronsPatronidReservationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExternalV1AgencyidPatronsPatronidReservationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addReservationsDeprecated
     *
     * Create new reservations for the patron (DEPRECATED)..
     *
     */
    public function testAddReservationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addReservationsV2
     *
     * Create new reservations for the patron..
     *
     */
    public function testAddReservationsV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteReservations
     *
     * Delete existing reservations..
     *
     */
    public function testDeleteReservations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReservations
     *
     * Get all unfulfilled reservations made by the patron (DEPRECATED)..
     *
     */
    public function testGetReservations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReservationsV2
     *
     * Get all unfulfilled reservations made by the patron..
     *
     */
    public function testGetReservationsV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateReservations
     *
     * Update existing reservations..
     *
     */
    public function testUpdateReservations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
