<?php
/**
 * ExternalAgencyidPatronsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FBS Adapter
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DPL\FBS\Test\Api;

use \DPL\FBS\Configuration;
use \DPL\FBS\ApiException;
use \DPL\FBS\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExternalAgencyidPatronsApiTest Class Doc Comment
 *
 * @category Class
 * @package  DPL\FBS
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExternalAgencyidPatronsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createV4
     *
     * Create a new patron who is a person..
     *
     */
    public function testCreateV4()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWithGuardian
     *
     * Creates a person patron with a guardian (eg A financial responsible)..
     *
     */
    public function testCreateWithGuardian()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPatronInformationByPatronIdV2
     *
     * Returns the patron details.
     *
     */
    public function testGetPatronInformationByPatronIdV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGuardian
     *
     * Updates a person patron's guardian (eg A financial responsible)..
     *
     */
    public function testUpdateGuardian()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateV5
     *
     * Update information about the patron..
     *
     */
    public function testUpdateV5()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
