<?php

namespace Drupal\dpl_admin\Services;

use Safe\Exceptions\JsonException;
use function Safe\file_get_contents;
use function Safe\json_decode;
use function Safe\preg_match;

/**
 * Helper for managing the CMS version, such as displaying it for admins.
 */
class VersionHelper {

  /**
   * Get the CMS version.
   *
   * Checks for the presence of a version file or a Git HEAD file and extracts
   * the version information accordingly. The retrieved version information is
   * then included as a requirement in the returned array.
   *
   * @remarks
   * The .version file is created and updated automatically within the
   * 'Publish source' Git workflow. It stores version information that can
   * be used to track and manage changes in the CMS.
   */
  public function getVersion(): ?string {

    $versionFile = DRUPAL_ROOT . '/../.version';
    $gitHeadFile = DRUPAL_ROOT . '/../.git/HEAD';
    $version = NULL;

    // Check for the .version file, which exists only in deployed
    // environments, as it's generated by a GitHub workflow.
    if (file_exists($versionFile)) {
      try {
        $data = json_decode(file_get_contents($versionFile));
      }
      catch (JsonException $e) {
        return $version;
      }

      $version = $data->version ?? NULL;

      return $version;
    }

    // Check if the .git/HEAD file exists.
    if (file_exists($gitHeadFile)) {
      // Read current git branch name from .git/HEAD.
      $head = file_get_contents($gitHeadFile);
      if (preg_match('/ref: refs\/heads\/([^\n]+)/', $head, $matches)) {
        $version = $matches[1] ?? NULL;
      }
    }

    return $version;
  }

}
