name: DB Data

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  db-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Our Taskfile requires a proper checkout to function because of
          # certain vars.
          fetch-depth: 0

      - name: Install go-task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup site
        run: task dev:reset

      - name: Create workspace for dump
        run: mkdir -p ${{ runner.temp }}/db-dump

      - name: Dump database
        run: |
          task dev:cli -- drush sql-dump --result-file=../database.sql
          mv database.sql ${{ runner.temp }}/db-dump/database.sql

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build db-dump image
        uses: docker/build-push-action@v6
        with:
          file: docker/db-dump.dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          context: ${{ runner.temp }}/db-dump
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository }}:db-dump
