on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
name: Platform integration

jobs:
  CheckDeployment:
    name: Check deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' }}
    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "pr-${{github.event.number}}"
          ref: ${{ github.head_ref }}
          log_args: true
      - name: Wait for environment to become available
        uses: nev7n/wait_for_response@v1
        with:
          url: 'https://varnish.pr-${{github.event.number}}.dpl-cms.dplplat01.dpl.reload.dk/'
          responseCode: 200
          # Time in ms. Wait for 10 mins for deployment to complete.
          timeout: 600000
          interval: 1000
      - name: Finish deployment
        if: always()
        uses: bobheadxi/deployments@v0.6.1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: 'https://varnish.pr-${{github.event.number}}.dpl-cms.dplplat01.dpl.reload.dk/'
          log_args: true

  CloseEnvironment:
    name: Close environment
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Close environment
        uses: bobheadxi/deployments@v0.6.1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "pr-${{github.event.number}}"
          log_args: true
