name: Test

on:
  push

env:
  BUILD_URL: 'https://github.comm/reload/poc-dpl-react-pr-trigger/releases/download/john'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: humourless-satisfactory-copperbutterfly

      - if: steps.check-branch-exists.outputs.exists == 'true'
        run: echo 'humourless-satisfactory-copperbutterfly Branch exists'

      - if: steps.check-branch-exists.outputs.exists == 'false'
        run: echo 'humourless-satisfactory-copperbutterfly Branch NOT FOUND'
