name: Test

on:
  push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Testing
        run: |
          echo ${{ env.TEST_ONE }}
        env:
          TEST_ONE: $(echo "${{ vars.ACCEPTED_BUILD_URL_PREFIXES }}" | jq --arg url "${{ env.BUILD_URL }}" 'any(.[]; . as $prefix | $url | contains($prefix))')

