name: Test

on:
  push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Testing
        run: |
            # echo ${{ toJson(env.HAS_ACCEPTED_BUILD_URL_PREFIX) }}
            echo ${{ env.TEST_ONE }}
        env:
          # ACCEPTED_BUILD_URL_PREFIXES: ${{ fromJson(vars.ACCEPTED_BUILD_URL_PREFIXES) }}
          # HAS_ACCEPTED_BUILD_URL_PREFIX: ${{ contains(env.BUILD_URL, fromJson(env.ACCEPTED_BUILD_URL_PREFIXES)[0]) || contains(env.BUILD_URL, fromJson(env.ACCEPTED_BUILD_URL_PREFIXES)[1]) }}
          TEST_ONE: echo "${{ vars.ACCEPTED_BUILD_URL_PREFIXES }}" | jq -r .[0]
