name: Test

on:
  push

env:
  BUILD_URL: 'https://github.comm/reload/poc-dpl-react-pr-trigger/releases/download/john'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Testing
        run: |
          BRANCH_EXISTS=$(git fetch origin develop || echo "John")
          echo "$BRANCH_EXISTS"
          # echo "BUILD_URL_IS_ACCEPTED=$BUILD_URL_IS_ACCEPTED" >> $GITHUB_ENV
      - name: Testing II
        run: |
          echo "Hello"
