<?php

/**
 * @file
 * Fix MySQL Collations
 */

/**
 * Implements hook_menu().
 *
 * Add confirm form for fixing database collations.
 *
 * @see collation_fixer_fix_collation_page()
 */
function collation_fixer_menu() {
  return array(
    'admin/collation-fixer/%/confirm' => array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('collation_fixer_fix_collation_confirm_form', 2),
      'access arguments' => array('fix database collation'),
      'file' => 'collation_fixer.admin.inc',
    ),
  );
}

/**
 * Check table collations.
 *
 * @param string $table
 *   Name of a table to check for collation correctness. Defaults to all tables.
 *
 * @return array
 *   A list of tables with wrong collations.
 */
function collation_fixer_check_collation($table = NULL) {
  $schema = _collation_fixer_get_schema($table);
  if (!is_null($table) && empty($schema[$table])) {
    drupal_set_message(t('Unknown table: @table', array('@table' => $table)), 'error');
    return FALSE;
  }

  $database_name = &drupal_static(__FUNCTION__);
  if (empty($database_name)) {
    $connection_options = Database::getConnection()->getConnectionOptions();
    $database_name = $connection_options['database'];
  }

  $fallback_charset = _collation_fixer_get_fallback_charset();
  $fallback_collation = _collation_fixer_get_fallback_collation();

  $wrong_collations = array();

  foreach ($schema as $table_name => $table_schema) {
    $schema_charset = !empty($table_schema['charset']) ? $table_schema['charset'] : $fallback_charset;
    $db_charset = db_query('SELECT CCSA.character_set_name FROM information_schema.`TABLES` T,information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation AND T.table_schema = :table_schema AND T.table_name = {:table_name}',
                  array(':table_schema' => $database_name, ':table_name' => $table_name))
      ->fetchField();

    $schema_collation = !empty($table_schema['collation']) ? $table_schema['collation'] : $fallback_collation;
    $db_collation = db_query('SELECT TABLE_COLLATION FROM information_schema.tables WHERE TABLE_SCHEMA = :table_schema AND TABLE_NAME = {:table_name}',
                 array(':table_schema' => $database_name, ':table_name' => $table_name))
      ->fetchField();

    if (($schema_charset != $db_charset) || ($schema_collation != $db_collation)) {
      $wrong_collations[] = $table_name;
    }
  }

  return $wrong_collations;
}

/**
 * Fix tables collations.
 *
 * @param string $table
 *   Name of a table to fix collation on. Defaults to all tables.
 *
 * @return bool
 *   TRUE if collations where changed successfully.
 */
function collation_fixer_fix_collation($table = NULL) {
  $schema = _collation_fixer_get_schema($table);
  if (!is_null($table) && empty($schema[$table])) {
    drupal_set_message(t('Unknown table: @table', array('@table' => $table)), 'error');
    return FALSE;
  }

  $fallback_charset = _collation_fixer_get_fallback_charset();
  $fallback_collation = _collation_fixer_get_fallback_collation();

  $status = TRUE;

  foreach ($schema as $table_name => $table_schema) {
    $charset = !empty($table_schema['charset']) ? $table_schema['charset'] : $fallback_charset;
    $collation = !empty($table_schema['collation']) ? $table_schema['collation'] : $fallback_collation;

    // Alter character set and collation of table definition.
    if ($result = db_query("ALTER TABLE {$table_name} CHARACTER SET $charset COLLATE $collation")->execute()) {
      $status = $status && $result;
    };

    // Alter character set and collation of table data.
    if ($result = db_query("ALTER TABLE {$table_name} CONVERT TO CHARACTER SET $charset COLLATE $collation")->execute()) {
      $status = $status && $result;
    };
  }

  return $status;
}

/**
 * Internal helper to get schema.
 *
 * @param string $table
 *   Name of a table to fix collation on. Defaults to all tables.
 *
 * @return array
 *   An array of schemes keyed by table name.
 */
function _collation_fixer_get_schema($table = NULL) {
  if (is_null($table)) {
    $schema = drupal_get_schema(NULL, TRUE);
  }
  else {
    $schema[$table] = drupal_get_schema($table, TRUE);
  }

  return $schema;
}

/**
 * Internal helper to get fallback charset.
 *
 * @return string
 *   The fallback charset to use.
 */
function _collation_fixer_get_fallback_charset() {
  $connection_options = Database::getConnection()->getConnectionOptions();
  if (isset($connection_options['charset'])) {
    $fallback_charset = $connection_options['charset'];
  }
  else {
    $fallback_charset = 'utf8mb4';
  }

  return $fallback_charset;
}

/**
 * Internal helper to get fallback collation.
 *
 * @return string
 *   The fallback collation to use.
 */
function _collation_fixer_get_fallback_collation() {
  $connection_options = Database::getConnection()->getConnectionOptions();
  if (isset($connection_options['collation'])) {
    $fallback_collation = $connection_options['collation'];
  }
  else {
    $fallback_collation = 'utf8_general_ci';
  }

  return $fallback_collation;
}
